import profile1 from '../images/profile.jpg';
import diamond from '../images/diamond.png';
import tickImage from '../images/tick.png';
import profile2 from '../images/elbert.jpg';
import bgImage1 from '../images/bg.jpg';
import bgImage2 from '../images/bg2.jpg';
import profile3 from '../images/virat.jpeg';
import bgImage3 from '../images/bg3.jpg';
import profile4 from '../images/vijay.jpg';
import bgImage4 from '../images/bg4.jpg';
const users = [
    {
      id: 1,
      name: "Aman Hussain Ansari",
      profileImage: profile1,
      diamondImage: diamond,
      tickImage: tickImage,
      bgImage: bgImage1,
      designation: "Programmer || Mern Stack Developer",
      followers: 123,
      following: 347,
      instagramUsername: "aman.json",
      stars: 1342,
      likes: 987,
      views: 5678,
      hearts: 2104,
      posts: [
        {
          id: 1,
          title: "Why Hire Me?",
          description: "I am a passionate and dedicated Full-Stack Developer with hands-on experience in technologies like React, Node.js, and MongoDB. My ability to learn quickly and adapt to new technologies allows me to contribute effectively to any project. Let's connect and discuss how I can bring value to your team!",
          likes: 25,
          author: "Aman",
          date: new Date().toLocaleDateString(),
          readTime: "3 min read",
          views: 102,
        },
        {
          id: 2,
          title: "Reflecting on My Work Experience",
          description: "Recently worked as a Full-Stack Developer at Deft Developers, where I honed my skills in Angular and PHP. Successfully delivered responsive and mobile-friendly web applications, identified and resolved critical bugs, and gained valuable insights into industry best practices.",
          likes: 18,
          author: "Aman",
          date: new Date().toLocaleDateString(),
          readTime: "2 min read",
          views: 89,
        },
        {
          id: 3,
          title: "Exciting New Project: Meme Generator",
          description: `Thrilled to share my latest project, a Meme Generator built using React and a Rest API. Users can create memes with just a click, choose from a vast library of 1000+ images, and enjoy a responsive and interactive user experience. Check it out and have some fun!`,
          likes: 35,
          author: "Aman",
          date: new Date().toLocaleDateString(),
          readTime: "4 min read",
          views: 143,
        },
    
      ],
    },
    {
        id: 2,
        name: "Albert Einstein",
        designation: "Theoretical Physicist",
        bgImage: bgImage2,
        profileImage: profile2,
      diamondImage: diamond,
      tickImage: tickImage,
        followers: 500,
        following: 10,
        instagramUsername: "einstein_universe",
        stars: 5000,
        likes: 10000,
        views: 1000,
        hearts: 800,
        posts: [
          {
            id: 1,
            title: "Theory of Relativity",
            description: "Exploring the concepts of special and general relativity. The universe is full of wonders waiting to be understood!",
            likes: 1200,
            author: "Albert",
            date: new Date().toLocaleDateString(),
            readTime: "5 min read",
            views: 5000,
          },
          {
            id: 2,
            title: "E=mc²: Unraveling the Equation",
            description: "Diving into the famous equation and its implications for understanding the relationship between mass and energy.",
            likes: 1800,
            author: "Albert",
            date: new Date().toLocaleDateString(),
            readTime: "4 min read",
            views: 7500,
          },
          {
            id: 3,
            title: "Quantum Mechanics Insights",
            description: "Discussing the fascinating world of quantum mechanics. Join me on this journey into the mysteries of the subatomic realm!",
            likes: 2500,
            author: "Albert",
            date: new Date().toLocaleDateString(),
            readTime: "6 min read",
            views: 9000,
          },
        
        ],
      },
      
      {
        id: 3,
        name: "Virat Kohli",
        profileImage: profile3,
        diamondImage: diamond,
        tickImage: tickImage,
        bgImage: bgImage3,
        designation: "International Cricketer",
        followers: 1000,
        following: 50,
        instagramUsername: "virat.kohli",
        stars: 20_000,
        likes: 1700,
        views: 10000,
        hearts: 2000,
        posts: [
          {
            id: 1,
            title: "The Cricket Journey",
            description: "Sharing insights into my cricket journey, the challenges, and the victories. Grateful for the love and support from fans around the world!",
            likes: 500,
            author: "Virat",
            date: new Date().toLocaleDateString(),
            readTime: "10 min read",
            views: 1000,
          },
          {
            id: 2,
            title: "Fitness and Discipline",
            description: "The importance of fitness and discipline in professional cricket. It's not just a sport; it's a way of life.",
            likes: 300,
            author: "Virat",
            date: new Date().toLocaleDateString(),
            readTime: "6 min read",
            views: 5000,
          },
          {
            id: 3,
            title: "Leading Team India",
            description: "Reflecting on the honor and responsibility of leading the Indian cricket team. The journey, the challenges, and the victories.",
            likes: 700,
            author: "Virat",
            date: new Date().toLocaleDateString(),
            readTime: "8 min read",
            views: 1500,
          },
          {
            id: 4,
            title: "Life Beyond Cricket",
            description: "Exploring interests beyond the cricket field. Balancing professional and personal life for a fulfilling and meaningful journey.",
            likes: 200,
            author: "Virat",
            date: new Date().toLocaleDateString(),
            readTime: "5 min read",
            views: 8000,
          },
        
        ],
      },
      {
        id: 4,
        name: "Vijay Thalapathy",
        profileImage: profile4,
        diamondImage: diamond,
        tickImage: tickImage,
        bgImage: bgImage4,
        designation: "Actor | Philanthropist",
        followers: 50000,
        following: 30,
        instagramUsername: "actorvijay",
        stars: 10_000,
        likes: 20000,
        views: 3000,
        hearts: 1000,
        posts: [
          {
            id: 1,
            title: "Cinema and Craft",
            description: "Exploring the art and craft of cinema. Every film is a new journey, and I'm grateful for the love and support of my fans.",
            likes: 300,
            author: "Vijay",
            date: new Date().toLocaleDateString(),
            readTime: "8 min read",
            views: 5000
          },
          {
            id: 2,
            title: "Social Impact Initiatives",
            description: "Sharing experiences and insights into social impact initiatives. Using the platform for positive change and contributing to society.",
            likes: 500,
            author: "Vijay",
            date: new Date().toLocaleDateString(),
            readTime: "10 min read",
            views: 8000,
          },
          {
            id: 3,
            title: "Memorable Movie Moments",
            description: "Reflecting on some of the memorable moments from my movies. Grateful for the opportunities to entertain and connect with the audience.",
            likes: 400,
            author: "Vijay",
            date: new Date().toLocaleDateString(),
            readTime: "7 min read",
            views: 7_000_0,
          },
          {
            id: 4,
            title: "Life Beyond the Silver Screen",
            description: "Balancing life as an actor and a philanthropist. The journey of self-discovery and making a positive impact on the world.",
            likes: 800,
            author: "Vijay",
            date: new Date().toLocaleDateString(),
            readTime: "12 min read",
            views: 10_000_0,
          },
        
        ],
      },
  
    ];
    
    export default users;
  